### ISSUE TITLE
you should take out comments/logs in production code 

### ISSUE THREAD

**Issue by ad3429** [bstofko/js-react-jamming#5]
https://github.com/bstofko/js-react-jamming/blob/master/src/util/Spotify.js#L17-L168

I noticed you have a few console.logs throughout your Spotify.js file. It's generally fine to use console.logs and comments when you're debugging your code, but usually in production code you want to remove these so that your code is clean, organized and can be followed easily.

**Comment by bstofko** [comment]
Removed debugging console.logs().
